"""HTML, CSV, and JSON report generation with Matplotlib charts."""

from __future__ import annotations

import json
import logging
import os
from datetime import UTC, datetime
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from virtual_silicon.analytics.analyzer import AnalyticsSummary
from virtual_silicon.database.models import Measurement, TestResult

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Silicon Validation Report — {execution_id}</title>
<style>
  body {{ font-family: Arial, sans-serif; margin: 20px; color: #333; background: #f9f9f9; }}
  h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 8px; }}
  h2 {{ color: #2980b9; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
  th {{ background: #3498db; color: white; padding: 8px 12px; text-align: left; }}
  td {{ padding: 8px 12px; border-bottom: 1px solid #ddd; }}
  tr:nth-child(even) {{ background: #f2f2f2; }}
  .pass {{ color: #27ae60; font-weight: bold; }}
  .fail {{ color: #e74c3c; font-weight: bold; }}
  .summary-box {{ background: white; border-radius: 6px; padding: 16px; margin-bottom: 16px;
                  box-shadow: 0 1px 3px rgba(0,0,0,0.12); display: inline-block; min-width: 160px; margin-right: 12px; }}
  .metric {{ font-size: 2em; font-weight: bold; color: #2c3e50; }}
  .metric-label {{ color: #7f8c8d; font-size: 0.9em; }}
  img {{ max-width: 100%; height: auto; margin-bottom: 16px; border-radius: 4px; }}
  .charts {{ display: flex; flex-wrap: wrap; gap: 12px; }}
  footer {{ margin-top: 40px; font-size: 0.8em; color: #95a5a6; }}
</style>
</head>
<body>
<h1>Virtual Silicon Validation Report</h1>
<h2>Executive Summary</h2>
<div>
  <div class="summary-box">
    <div class="metric">{total_tests}</div>
    <div class="metric-label">Total Tests</div>
  </div>
  <div class="summary-box">
    <div class="metric pass">{passed}</div>
    <div class="metric-label">Passed</div>
  </div>
  <div class="summary-box">
    <div class="metric fail">{failed}</div>
    <div class="metric-label">Failed</div>
  </div>
  <div class="summary-box">
    <div class="metric">{pass_rate}%</div>
    <div class="metric-label">Pass Rate</div>
  </div>
  <div class="summary-box">
    <div class="metric">{avg_duration_ms:.1f} ms</div>
    <div class="metric-label">Avg Duration</div>
  </div>
</div>

<h2>Run Information</h2>
<table>
  <tr><th>Field</th><th>Value</th></tr>
  <tr><td>Execution ID</td><td>{execution_id}</td></tr>
  <tr><td>Generated At</td><td>{generated_at}</td></tr>
  <tr><td>Firmware Version</td><td>{firmware_version}</td></tr>
  <tr><td>Chip Version</td><td>{chip_version}</td></tr>
  <tr><td>Avg Voltage</td><td>{avg_voltage}</td></tr>
  <tr><td>Avg Current</td><td>{avg_current}</td></tr>
  <tr><td>Avg Temperature</td><td>{avg_temperature}</td></tr>
</table>

<h2>Failures by Category</h2>
{failures_by_category_table}

<h2>Slowest Tests</h2>
{slowest_tests_table}

<h2>Charts</h2>
<div class="charts">
{chart_images}
</div>

<h2>Recommendations</h2>
<ul>
  {recommendations}
</ul>

<h2>Downloads</h2>
<ul>
  <li><a href="{csv_file}">CSV Summary</a></li>
  <li><a href="{json_file}">JSON Results</a></li>
</ul>

<footer>Generated by Virtual Silicon Validation Platform v1.0.0 &mdash; {generated_at}</footer>
</body>
</html>
"""


class ReportGenerator:
    """Generates HTML, CSV, JSON reports and Matplotlib chart images."""

    def __init__(
        self,
        output_dir: str | Path = "reports",
        firmware_version: str = "1.0",
        chip_version: str = "VS-1000-A",
    ) -> None:
        """Initialize the report generator.

        Args:
            output_dir: Directory where reports and charts are saved.
            firmware_version: Firmware version string for metadata.
            chip_version: Chip version string for metadata.
        """
        self._output_dir = Path(output_dir)
        self._charts_dir = self._output_dir / "charts"
        self._firmware_version = firmware_version
        self._chip_version = chip_version
        self._output_dir.mkdir(parents=True, exist_ok=True)
        self._charts_dir.mkdir(parents=True, exist_ok=True)

    def generate_all(
        self,
        summary: AnalyticsSummary,
        results: list[TestResult],
        measurements: list[Measurement],
    ) -> dict[str, Path]:
        """Generate all reports and charts.

        Args:
            summary: Computed analytics summary.
            results: List of TestResult ORM objects.
            measurements: List of Measurement ORM objects.

        Returns:
            Dictionary mapping report type to file path.
        """
        eid = summary.execution_id
        chart_paths = self._generate_charts(summary, measurements)
        csv_path = self._generate_csv(results, eid)
        json_path = self._generate_json(summary, eid)
        html_path = self._generate_html(summary, chart_paths, csv_path, json_path)

        logger.info("Reports generated in %s.", self._output_dir)
        return {
            "html": html_path,
            "csv": csv_path,
            "json": json_path,
            "charts": chart_paths.get("pass_fail", self._charts_dir),
        }

    def _generate_charts(
        self, summary: AnalyticsSummary, measurements: list[Measurement]
    ) -> dict[str, Path]:
        paths: dict[str, Path] = {}

        # Pass/Fail pie chart
        fig, ax = plt.subplots(figsize=(5, 4))
        labels = ["Passed", "Failed"]
        values = [summary.passed, summary.failed]
        colors = ["#27ae60", "#e74c3c"]
        non_zero = [(lbl, v, c) for lbl, v, c in zip(labels, values, colors, strict=False) if v > 0]
        if non_zero:
            ax.pie(
                [x[1] for x in non_zero],
                labels=[x[0] for x in non_zero],  # noqa: E501
                colors=[x[2] for x in non_zero],
                autopct="%1.1f%%",
                startangle=90,
            )
            ax.set_title("Test Results Overview")
            p = self._charts_dir / "pass_fail.png"
            fig.savefig(p, bbox_inches="tight", dpi=96)
            paths["pass_fail"] = p
        plt.close(fig)

        # Failures by category
        if summary.failures_by_category:
            fig, ax = plt.subplots(figsize=(7, 4))
            cats = list(summary.failures_by_category.keys())
            counts = list(summary.failures_by_category.values())
            ax.bar(cats, counts, color="#e74c3c")
            ax.set_title("Failures by Category")
            ax.set_xlabel("Category")
            ax.set_ylabel("Failure Count")
            plt.xticks(rotation=30, ha="right")
            p = self._charts_dir / "failures_by_category.png"
            fig.savefig(p, bbox_inches="tight", dpi=96)
            paths["failures_by_category"] = p
            plt.close(fig)

        # Measurement trends from ORM objects
        if measurements:
            rows = [
                {
                    "voltage": getattr(m, "voltage", None),
                    "current": getattr(m, "current", None),
                    "temperature": getattr(m, "temperature", None),
                }
                for m in measurements
            ]
            mdf = pd.DataFrame(rows)

            for metric, color, unit in [
                ("voltage", "#3498db", "V"),
                ("current", "#e67e22", "A"),
                ("temperature", "#e74c3c", "°C"),
            ]:
                series = mdf[metric].dropna()
                if not series.empty:
                    fig, ax = plt.subplots(figsize=(7, 3))
                    ax.plot(series.values, color=color, linewidth=1.5)
                    ax.set_title(f"{metric.capitalize()} Over Time")
                    ax.set_xlabel("Sample")
                    ax.set_ylabel(unit)
                    ax.grid(True, alpha=0.3)
                    p = self._charts_dir / f"{metric}_trend.png"
                    fig.savefig(p, bbox_inches="tight", dpi=96)
                    paths[f"{metric}_trend"] = p
                    plt.close(fig)

        return paths

    def _generate_csv(self, results: list[TestResult], execution_id: str) -> Path:
        rows = []
        for r in results:
            rows.append(
                {
                    "execution_id": getattr(r, "execution_id", execution_id),
                    "test_name": getattr(r, "test_name", ""),
                    "category": getattr(r, "category", ""),
                    "status": getattr(r, "status", ""),
                    "duration_ms": getattr(r, "duration_ms", 0.0),
                    "error_message": getattr(r, "error_message", ""),
                }
            )
        df = pd.DataFrame(rows) if rows else pd.DataFrame()
        path = self._output_dir / f"{execution_id}_results.csv"
        df.to_csv(path, index=False)
        return path

    def _generate_json(self, summary: AnalyticsSummary, execution_id: str) -> Path:
        data = {
            "execution_id": execution_id,
            "generated_at": datetime.now(UTC).isoformat(),
            "firmware_version": self._firmware_version,
            "chip_version": self._chip_version,
            "summary": {
                "total_tests": summary.total_tests,
                "passed": summary.passed,
                "failed": summary.failed,
                "pass_rate": summary.pass_rate,
                "avg_duration_ms": summary.avg_duration_ms,
                "avg_voltage": summary.avg_voltage,
                "avg_current": summary.avg_current,
                "avg_temperature": summary.avg_temperature,
            },
            "failures_by_category": summary.failures_by_category,
            "slowest_tests": summary.slowest_tests,
            "most_common_faults": summary.most_common_faults,
        }
        path = self._output_dir / f"{execution_id}_report.json"
        with path.open("w") as f:
            json.dump(data, f, indent=2)
        return path

    def _generate_html(
        self,
        summary: AnalyticsSummary,
        chart_paths: dict[str, Path],
        csv_path: Path,
        json_path: Path,
    ) -> Path:
        eid = summary.execution_id
        generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

        # Failures table
        if summary.failures_by_category:
            rows = "".join(
                f"<tr><td>{cat}</td><td>{cnt}</td></tr>"
                for cat, cnt in summary.failures_by_category.items()
            )
            failures_table = f"<table><tr><th>Category</th><th>Count</th></tr>{rows}</table>"
        else:
            failures_table = "<p>No failures recorded.</p>"

        # Slowest tests table
        if summary.slowest_tests:
            rows = "".join(
                f"<tr><td>{t.get('test_name', '')}</td>"
                f"<td>{t.get('duration_ms', 0):.2f}</td>"
                f'<td class="{"pass" if t.get("status") == "PASS" else "fail"}">'
                f"{t.get('status', '')}</td></tr>"
                for t in summary.slowest_tests
            )
            slowest_table = (
                f"<table><tr><th>Test</th><th>Duration (ms)</th><th>Status</th></tr>{rows}</table>"
            )
        else:
            slowest_table = "<p>No test duration data.</p>"

        # Chart images (relative paths)
        chart_imgs = ""
        for name, path in chart_paths.items():
            rel = os.path.relpath(path, self._output_dir)
            chart_imgs += f'<div><img src="{rel}" alt="{name}"></div>'

        # Recommendations
        recs = []
        if summary.fail_rate > 0:
            recs.append(f"Investigate {summary.failed} failing test(s).")
        if summary.avg_temperature and summary.avg_temperature > 70:
            recs.append("Average temperature is elevated — review thermal management.")
        if summary.avg_voltage and summary.avg_voltage < 3.0:
            recs.append("Average voltage below nominal — check power supply stability.")
        if not recs:
            recs.append("All checks nominal. No immediate action required.")
        recs_html = "".join(f"<li>{r}</li>" for r in recs)

        html = HTML_TEMPLATE.format(
            execution_id=eid,
            generated_at=generated_at,
            firmware_version=self._firmware_version,
            chip_version=self._chip_version,
            total_tests=summary.total_tests,
            passed=summary.passed,
            failed=summary.failed,
            pass_rate=summary.pass_rate,
            avg_duration_ms=summary.avg_duration_ms,
            avg_voltage=f"{summary.avg_voltage:.3f}V" if summary.avg_voltage else "N/A",
            avg_current=f"{summary.avg_current:.4f}A" if summary.avg_current else "N/A",
            avg_temperature=f"{summary.avg_temperature:.2f}°C"
            if summary.avg_temperature
            else "N/A",
            failures_by_category_table=failures_table,
            slowest_tests_table=slowest_table,
            chart_images=chart_imgs,
            recommendations=recs_html,
            csv_file=csv_path.name,
            json_file=json_path.name,
        )

        path = self._output_dir / f"{eid}_report.html"
        with path.open("w") as f:
            f.write(html)
        return path
